### ISSUE TITLE
No support for via-ir?

### ISSUE THREAD

**Issue by naps62** [defi-wonderland/natspec-smells#57]
I have a foundry project where I just enabled `via_ir`, and moved to using the new `require(bool, CustomError())` syntax (which does require via-ir)

natspec-smells now throws an error. it seems it fails to use the via-ir flag in its own internal compilation

```
CompileFailedError: Compiler Errors: ==== 0.8.26 ====:
 UnimplementedFeatureError: Require with a custom error is only available using the via-ir pipeline.



    at compileSol (/home/naps62/.../fund/node_modules/solc-typed-ast/dist/compile/utils.js:178:11)
    at async getProjectCompiledSources (/home/naps62/.../fund/node_modules/@defi-wonderland/natspec-smells/lib/utils.js:18:27)
    at async /home/naps62/.../fund/node_modules/@defi-wonderland/natspec-smells/lib/main.js:17:25 {
  failures: [ { compilerVersion: '0.8.26', errors: [Array] } ]
}
```

**Comment by gas1cent** [comment]
@naps62 thanks for the report, we'll take a look at this shortly.
